### ISSUE TITLE
Missing license for the code

### ISSUE THREAD

**Issue by zoffixznet** [rakudup/rakudup.github.io#4]
What license is this code distributed under?

**Comment by stmuk** [comment]
The Artistic License 2.0

The lack of licence in this repo is due to there being two repos (an artefact existing due to me thinking of the website after the code) and its in the "other" repo.

https://github.com/stmuk/rakudup/issues/6 exists for me to merge the two (which I shall do now!)

**Comment by stmuk** [comment]
Repos merged.
