### ISSUE TITLE
rakudup fails when trying to determine rakudo release

### ISSUE THREAD

**Issue by avuserow** [rakudup/rakudup.github.io#9]
rakudup fails when trying to get the VERSION file from Rakudo's master branch.

```
fatal: Path 'VERSION' does not exist in 'master'
```

Looks like the file was deleted in April 2019 and rakudup will need to find an alternate way of determining the latest rakudo version.

**Comment by stmuk** [comment]
The file has been moved as part of refactoring upstream to 

https://github.com/rakudo/rakudo/blob/master/tools/templates/VERSION

It still contains 2019.03.1 since there hasn't been a release since then. I'll update rakudup when upstream releases.

**Comment by stmuk** [comment]
Looks like upstream reverted the move.

https://github.com/rakudo/rakudo/commit/33844cb4bec35b0f12bb280bd5ba760aeca7f79a

**Comment by stmuk** [comment]
works
